# Generated by Django 6.0.2 on 2026-02-09 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('transactions', '0004_transaction_close_date_transaction_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='client_name',
        ),
        migrations.AddField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='transactions.contact'),
        ),
    ]
