# Generated by Django 6.0.2 on 2026-02-09 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_remove_deal_client_name_deal_contact'),
        ('transactions', '0005_transaction_detailed_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='transactions.property'),
        ),
    ]
