# Generated by Django 6.0.2 on 2026-02-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
