# Generated by Django 6.0.2 on 2026-02-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Single Family', 'Single Family'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Multi-Family', 'Multi-Family'), ('Land', 'Land')], default='Single Family', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Sold', 'Sold')], default='Active', max_length=20),
        ),
    ]
