# Generated by Django 6.0.2 on 2026-02-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_property_bathrooms_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Agent', 'Agent'), ('Other', 'Other')], default='Buyer', max_length=20),
        ),
    ]
