# Generated by Django 6.0.2 on 2026-02-08 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_config', '0001_initial'),
        ('transactions', '0003_contact_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stage',
            field=models.CharField(choices=[('Prospect', 'Prospect'), ('Active', 'Active'), ('Under Contract', 'Under Contract'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Prospect', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Deal Value', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Percentage (e.g. 2.50)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core_config.transactionstatus'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core_config.transactiontype'),
        ),
    ]
