# Generated by Django 6.0.2 on 2026-02-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_close_date_transaction_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='detailed_status',
            field=models.CharField(blank=True, help_text='Specific status details', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Single Family', 'Single Family'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Multi-Family', 'Multi-Family'), ('Land', 'Land')], max_length=50, null=True),
        ),
    ]
